#! /bin/sh

#Load ~ to mpd if not already
if [[ $( mpc | wc -l ) -gt 1 ]]
then
	echo "" >> /dev/null
else
	mpc clear
	mpc add youtube-dl
fi

$HOME/.config/polybar/launch.sh --forest &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend &
feh --bg-fill /home/ashton/.config/split_catppuccin.png &
dunst -config /home/ashton/.config/dunst/dunstrc &
# light-locker &
clipcatd -r &
#mpc add youtube-dl &
bspc monitor $(bspc query -M --names) -d I II III IV V
#bspc monitor LVDS1 -d I II III IV V
#bspc monitor HDMI-0 -d VI VII VIII IX x

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#Testing bare
