#! /bin/sh

#Load ~ to mpd if not already
if [[ $( mpc | wc -l ) -gt 1 ]]
then
	echo "" >> /dev/null
else
	mpc clear
	mpc add youtube-dl
fi

$HOME/.config/polybar/launch.sh --forest &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend &
feh --bg-fill /home/ashton/.config/split_catppuccin.png &
dunst -config /home/ashton/.config/dunst/dunstrc &
# light-locker &
clipcatd -r &
#mpc add youtube-dl &
bspc monitor $(bspc query -M --names) -d I II III IV V
#bspc monitor LVDS1 -d I II III IV V
#bspc monitor HDMI-0 -d VI VII VIII IX x

gap=15 # Window gap value
bspc config border_width         2
bspc config window_gap           $gap

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config adaptative_raise true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' private=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config top_padding $(($PANEL_HEIGHT-gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap
##Color settings
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#C3BAC6"
bspc config normal_border_color "#6E6C7E"
bspc config presel_border_color "#FAE3B0"
bspc config urgent_border_color "#F28FAD"
bspc config focused_private_border_color "#35BF5C"

bspc config focus_follows_pointer true
