server_host = '127.0.0.1'
server_port = 45045
finder = 'rofi'

[rofi]
line_length = 100
menu_length = 30

[dmenu]
line_length = 100
menu_length = 30

[custom]
program = 'rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/polybar/forest/scripts/rofi/launcher.rasi'
args = []
